name = "ProjectTemplate"
uuid = "1837bf2e-e1bd-4166-9afa-9b5fc6617024"
authors = ["Niklas Korsbo <niklas.korsbo@slcu.cam.ac.uk>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
